In [1]:
import pandas as pd
import sqlite3

In [7]:
# conectamos con la base de datos my_database.db
connection = sqlite3.connect("database_cervezas.db")

# obtenemos un cursor que utilizamos para las queries
crsr = connection.cursor()

In [2]:
# Con esta función leemos los datos y lo pasamos a un DataFrame de Pandas
def sql_query(query):

    # Ejecuta la query
    crsr.execute(query)

    # Almacena los datos de la query 
    ans = crsr.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in crsr.description]

    return pd.DataFrame(ans,columns=names)

In [8]:
res = crsr.execute("SELECT name FROM sqlite_master WHERE type='table'")
for name in res:
    print(name[0])

cervezas
bares
empleados
reparto

In [50]:
# Crear las tablas
crsr.executescript("""
DROP TABLE IF EXISTS reparto;
DROP TABLE IF EXISTS cervezas;
DROP TABLE IF EXISTS bares;
DROP TABLE IF EXISTS empleados;

CREATE TABLE cervezas(
    codC INT PRIMARY KEY,
    envase TEXT,
    capacidad REAL,
    stock INT
);

CREATE TABLE bares(
    codB INT PRIMARY KEY,
    nombre TEXT,
    cif TEXT,
    localidad TEXT
);

CREATE TABLE empleados(
    codE INT PRIMARY KEY,
    nombre TEXT,
    sueldo INT
);

CREATE TABLE reparto (
    codE INT,
    codB INT,
    codC INT,
    fecha DATE,
    cantidad INT,

    PRIMARY KEY (codE, codB, codC),

    FOREIGN KEY (codE) REFERENCES empleados(codE),
    FOREIGN KEY (codB) REFERENCES bares(codB),
    FOREIGN KEY (codC) REFERENCES cervezas(codC)
);
""")
crsr.executescript("""
-- CERVEZAS
INSERT INTO cervezas VALUES (1, 'Botella', 0.2, 3600);
INSERT INTO cervezas VALUES (2, 'Botella', 0.33, 1200);
INSERT INTO cervezas VALUES (3, 'Lata', 0.33, 2400);
INSERT INTO cervezas VALUES (4, 'Botella', 1, 288);
INSERT INTO cervezas VALUES (5, 'Barril', 60, 30);

-- BARES
INSERT INTO bares VALUES (1, 'Stop', '11111111X', 'Villa Botijo');
INSERT INTO bares VALUES (2, 'Las Vegas', '22222222Y', 'Villa Botijo');
INSERT INTO bares VALUES (3, 'Club Social', NULL, 'Las Ranas');
INSERT INTO bares VALUES (4, 'Otra Ronda', '33333333Z', 'La Esponja');

-- EMPLEADOS
INSERT INTO empleados VALUES (1, 'Carlos Lopez', 120000);
INSERT INTO empleados VALUES (2, 'Rosa Perez', 110000);
INSERT INTO empleados VALUES (3, 'Luisa Garcia', 100000);

-- REPARTO
INSERT INTO reparto VALUES (1, 1, 1, '2005-10-21', 240);
INSERT INTO reparto VALUES (1, 1, 2, '2005-10-21', 48);
INSERT INTO reparto VALUES (1, 2, 3, '2005-10-22', 60);
INSERT INTO reparto VALUES (1, 4, 5, '2005-10-22', 4);
INSERT INTO reparto VALUES (2, 2, 3, '2005-10-22', 48);
INSERT INTO reparto VALUES (2, 2, 5, '2005-10-23', 2);
INSERT INTO reparto VALUES (2, 4, 1, '2005-10-23', 480);
INSERT INTO reparto VALUES (2, 4, 2, '2005-10-24', 72);
INSERT INTO reparto VALUES (3, 3, 3, '2005-10-24', 48);
INSERT INTO reparto VALUES (3, 3, 4, '2005-10-25', 20);
""")

In [ ]:
query = '''

'''

crsr.execute(query)

In [ ]:
query = '''

'''

crsr.execute(query)

In [ ]:
query = '''

'''

crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
# CRUD Create Register(insert) Update Delete
crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
sql_query(query)

  CodE CodB CodC       Fecha  Cantidad
0    1  001   01  2005-10-21       240
1    1  001   02  2005-10-21        48
2    1  002   03  2005-10-22        60
3    1  004   05  2005-10-22         4
4    2  002   03  2005-10-22        48
5    2  002   05  2005-10-23         2
6    2  004   01  2005-10-23       480
7    2  004   02  2005-10-24        72
8    3  003   03  2005-10-24        48
9    3  003   04  2005-10-25        20

In [25]:
# 1 Obtener el nombre de los empleados que hayan repartido al bar Stop durante la semana 
# del 17 al 23 de octubre de 2005.

query = """
    SELECT DISTINCT e.nombre AS empleado, b.nombre AS bar
    FROM empleados e
    INNER JOIN reparto r ON e.codE = r.codE
    INNER JOIN bares b ON r.codB = b.codB
    where b.nombre = "Stop" and r.fecha BETWEEN '2005-10-17' AND '2005-10-21';
"""

sql_query(query)

       empleado   bar
0  Carlos Lopez  Stop

In [38]:
# 2 Obtener el Cif y nombre de los bares a los que se ha repartido cerveza de tipo Botella y
# capacidad inferior a 1 litro, ordenados por localidad

query = '''

SELECT DISTINCT b.cif, b.nombre
FROM bares b
INNER JOIN reparto r
    ON b.codB = r.codB
INNER JOIN cervezas c
    ON r.codC = c.codC
WHERE c.envase = 'Botella'
    AND c.capacidad < 1
ORDER BY b.localidad;

'''

sql_query(query)

         cif      nombre
0  33333333Z  Otra Ronda
1  11111111X        Stop

In [ ]:
# 3. Obtener los repartos (nombre del bar, envase y capacidad de la bebida, fecha y cantidad)

query = '''
 SELECT b.nombre, c.envase, c.capacidad, r.fecha, r.cantidad
FROM bares b
INNER JOIN reparto r
    ON b.codB = r.codB
INNER JOIN cervezas c
    ON r.codC = c.codC
'''

sql_query(query)

        nombre   envase  capacidad       fecha  cantidad
0         Stop  Botella       0.20  2005-10-21       240
1         Stop  Botella       0.33  2005-10-21        48
2    Las Vegas     Lata       0.33  2005-10-22        60
3   Otra Ronda   Barril      60.00  2005-10-22         4
4    Las Vegas     Lata       0.33  2005-10-22        48
5    Las Vegas   Barril      60.00  2005-10-23         2
6   Otra Ronda  Botella       0.20  2005-10-23       480
7   Otra Ronda  Botella       0.33  2005-10-24        72
8  Club Social     Lata       0.33  2005-10-24        48
9  Club Social  Botella       1.00  2005-10-25        20

In [ ]:
# 4. Obtener los bares a los que se les ha repartido envases de tipo botella y capacidad 0.2 o
# 0.33

query = '''
select distinct b.nombre 
from cervezas c
inner join reparto r 
    on c.codC = r.codC
inner join bares b 
    on r.codB = b.codB
    where c.envase = "Botella" and c.capacidad BETWEEN 0.2 and 0.33 ;
'''
sql_query(query)

       nombre
0        Stop
1  Otra Ronda

In [ ]:
# 5. Nombre de los empleados que han repartido a los bares "Stop" y "Las Vegas" cervezas con
# envase botella.

query = '''
select e.nombre
from empleados e
inner join reparto r
    on e.codE = r.codE
inner join cervezas c
    on r.codC = c.codC
inner join bares b
    on b.codB = r.codB
where b.nombre = "Stop" and b.nom
'''
sql_query(query)

         nombre
0  Carlos Lopez
1  Carlos Lopez

In [20]:
# 6. Obtener el nombre y número de viajes que ha realizado cada empleado fuera de Villa
# Botijo.

query = '''
select e.nombre, count(*)
from empleados e
    inner join reparto r
    on e.codE = r.codE
    inner join bares b
    on r.codB = b.codB
    where b.localidad is not "Villa Botijo"
    group by e.nombre
'''
sql_query(query)

         nombre  count(*)
0  Carlos Lopez         1
1  Luisa Garcia         2
2    Rosa Perez         2

In [ ]:
query = '''

'''
sql_query(query)

       Nombre   Localidad  litros
0  Otra Ronda  La Esponja  359.76

In [25]:
# 7. Obtener el nombre y localidad del bar que más litros de cerveza ha comprado.

query = """
select b.nombre, b.localidad,
       sum(r.cantidad * c.capacidad) AS litros
from bares b
inner join reparto r ON b.codB = r.codB
inner join cervezas c ON r.codC = c.codC
group by b.codB, b.nombre, b.localidad
order by litros desc
LIMIT 1;
"""

sql_query(query)

       nombre   localidad  litros
0  Otra Ronda  La Esponja  359.76

In [37]:
# 8. Obtener los bares que han adquirido todos los tipos de cerveza con envase de botella y
# capacidad menor que 1 litro.

query = '''
select  b.nombre, count(distinct c.codC) 
from bares b
inner join reparto r ON b.codB = r.codB
inner join cervezas c ON r.codC = c.codC
where c.envase = 'Botella'
  and c.capacidad < 1
group by b.codB, b.nombre;
'''
sql_query(query)

       nombre  count(distinct c.codC)
0        Stop                       2
1  Otra Ronda                       2

In [51]:
# 9. Subir un 5% el sueldo del empleado que más días haya trabajado.

query = '''
UPDATE empleados
SET sueldo = sueldo * 1.05
WHERE codE = (
    SELECT e.codE
    FROM empleados e
    INNER JOIN reparto r
        ON e.codE = r.codE
    GROUP BY e.codE
    ORDER BY COUNT(DISTINCT r.fecha) DESC
    LIMIT 1
);
'''

crsr.execute(query)
crsr.connection.commit()

sql_query("SELECT * FROM empleados;")

   codE        nombre  sueldo
0     1  Carlos Lopez  120000
1     2    Rosa Perez  115500
2     3  Luisa Garcia  100000

In [ ]:
query = '''

'''
sql_query(query)

   t.Sueldo * 1.05
0         115500.0

In [ ]:
query = '''
   
'''
sql_query(query)

  CodE
0    2

In [ ]:
query = '''

'''
crsr.execute(query)

In [ ]:
query = '''

'''
sql_query(query)

  CodE      Nombre  Sueldo
0    2  Rosa Perez  115500